### ISSUE TITLE
HTML 마크업 

### ISSUE THREAD

**Issue by y00eunji** [ConnecTo-FrontEnd/stopstop#1]
## 할 일
- [x] index.html 만들기

**Comment by SleeplessN** [comment]
마크업 진행하시면 css 작업하도록 하겠습니다~

**Comment by SleeplessN** [comment]
현재 저는 git flow 설정중입니다

**Comment by y00eunji** [comment]
> 마크업 진행하시면 css 작업하도록 하겠습니다~

좋습니다 저돕니다 모르시면 바로 댓글 다시죠 질문 한 100개입니다
